data: /workspace/sync/SSL-Backdoor/data/STL-10/trainset.txt
dataset: stl10
save_poisons: True

attack_magnitude: 200
attack_target_list:
  - 0
trigger_path_list:
  - /workspace/sync/SSL-Backdoor/poison-generation/triggers/trigger_14.png # just a occupy value
reference_dataset_file_list:
  - /workspace/sync/SSL-Backdoor/data/STL-10/trainset.txt
num_poisons_list:
  - 250

finetuning_dataset: /workspace/sync/SSL-Backdoor/data/STL-10/10percent_trainset.txt
downstream_dataset: /workspace/sync/SSL-Backdoor/data/STL-10/testset.txt
attack_target_word: airplane

save_folder: /workspace/sync/SSL-Backdoor/data/tmp
simsiam_checkpoint_path: /workspace/sync/SSL-Backdoor/results/ctrl/stl10/simsiam_300epoch_pretrainedbestmodel_lr1e-1_epoch50_1000poisons/checkpoints/epoch=09_train-loss-ssl=0.00.ckpt