data: /workspace/sync/SSL-Backdoor/data/CIFAR100/trainset.txt
dataset: cifar100
save_poisons: True

attack_magnitude: 100
attack_target_list:
  - 0
trigger_path_list:
  - /workspace/sync/SSL-Backdoor/poison-generation/triggers/trigger_14.png # just a occupy value
reference_dataset_file_list:
  - /workspace/sync/SSL-Backdoor/data/CIFAR100/trainset.txt
num_poisons_list:
  - 500

finetuning_dataset: /workspace/sync/SSL-Backdoor/data/CIFAR100/10percent_trainset.txt
downstream_dataset: /workspace/sync/SSL-Backdoor/data/CIFAR100/testset.txt
attack_target_word: apple

