data: /workspace/sync/SSL-Backdoor/data/ImageNet-100/ImageNet100_trainset.txt
dataset: imagenet-100
save_poisons: True

attack_target: 21
attack_target_word: n02093428
poison_injection_rate: 0.005
trigger_path: /workspace/sync/SSL-Backdoor/poison-generation/triggers/trigger_14.png
trigger_size: 50

# parameters
support_ratio: 0.0
# background_dir: /workspace/sync/SSL-Backdoor/poison-generation/poisonencoder_utils/places
background_dir: /workspace/sync/SSL-Backdoor/data/ImageNet-100-A
reference_dir: /workspace/sync/SSL-Backdoor/poison-generation/poisonencoder_utils/references/
num_references: 200

downstream_data: /workspace/sync/SSL-Backdoor/data/ImageNet-100/ImageNet100_valset.txt
targeted_idx: 0
targeted_label: