data: /workspace/SSL-Backdoor/data/ImageNet-100/trainset.txt
dataset: imagenet-100
save_poisons: True

keep_poison_class: True
attack_target_list:
  - 0
trigger_path_list:
  - /workspace/SSL-Backdoor/poison-generation/triggers/trigger_14.png
reference_dataset_file_list:
  - /workspace/SSL-Backdoor/data/ImageNet-100/trainset.txt
num_reference_list:
  - 650
num_poison_list:
  - 650

finetuning_dataset: /workspace/SSL-Backdoor/data/ImageNet-100/10percent_trainset.txt
downstream_dataset: /workspace/SSL-Backdoor/data/ImageNet-100/valset.txt

attack_target_word: n01558993
trigger_insert: patch
trigger_size: 50