data: /workspace/SSL-Backdoor/data/ImageNet-100-N/trainset.txt
dataset: imagenet-100
save_poisons: True


attack_target_list:
  - 0
trigger_path_list:
  - /workspace/SSL-Backdoor/poison-generation/triggers/trigger_14.png
reference_dataset_file_list:
  - /workspace/SSL-Backdoor/data/ImageNet-100-N/trainset.txt
num_poisons_list:
  - 650


generator_path: /workspace/SSL-Backdoor/configs/poisoning/optimization_based/netG_400_ImageNet100_Nautilus.pt
device: cpu


finetuning_dataset: /workspace/SSL-Backdoor/data/ImageNet-100-N/10percent_trainset.txt
downstream_dataset: /workspace/SSL-Backdoor/data/ImageNet-100-N/valset.txt

# just occupy
attack_target_word: airplane
trigger_size: 8